spring:
  datasource:
    username: ${USER}
    url: ${DATABASE_CONNECTION_URL}
    password: ${PASSWORD}
  flyway:
    baseline-on-migrate: 'true'
  jpa:
    hibernate:
      ddl-auto: update
api:
  security:
    token:
      secret: ${JWT_SECRET:17712e23-a5fd-4d9e-89af-7c79e97c8b42}
